//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Edges
    {
        public int FromNode { get; set; }
        public int ToNode { get; set; }
        public int Weight { get; set; }
    }
}
